config/routes.rb
Rails3MongoidDevise::Application.routes.draw do
  resources :favorites

  resources :trucks

  root :to => "home#index"

  devise_for :users
  resources :users, :only => :show

end

app/models/favorite.rb
class Favorite
  include Mongoid::Document
  belongs_to :user
  has_one :truck
end

app/models/truck.rb
class Truck
  include Mongoid::Document
  include Mongoid::FullTextSearch
  include Mongoid::Spacial::Document
  #include Geocoder::Model::Mongoid  

  field :name, :type => String
  field :twitter, :type => String
  field :city, :type => String
  field :address, :type => String
  field :location, :type => Array, spacial: {lat: :latitude, lng: :longitude, return_array: true }


  # geocoded_by :address               # can also be an IP address
  # after_validation :geocode          # auto-fetch coordinates

  # reverse_geocoded_by :location
  # after_validation :reverse_geocode  # auto-fetch address

  has_and_belongs_to_many :users

  # after_save :update_index
  # after_create :update_index
  # after_update :update_index
  # after_destroy :update_index 

  # def update_index
  #   Truck.update_ngram_index
  # end

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :name
  field :email
  field :encrypted_password
  field :current_sign_in_at
  field :last_sign_in_at
  field :current_sign_in_ip
  field :last_sign_in_ip
  field :sign_in_count
  field :remember_created_at
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_and_belongs_to_many :trucks
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # GET /favorites
  # GET /favorites.xml
  def index
    @favorites = Favorite.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @favorites }
    end
  end

  # GET /favorites/1
  # GET /favorites/1.xml
  def show
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # GET /favorites/new
  # GET /favorites/new.xml
  def new
    @favorite = Favorite.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # GET /favorites/1/edit
  def edit
    @favorite = Favorite.find(params[:id])
  end

  # POST /favorites
  # POST /favorites.xml
  def create
    @favorite = Favorite.new(params[:favorite])

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to(@favorite, :notice => 'Favorite was successfully created.') }
        format.xml  { render :xml => @favorite, :status => :created, :location => @favorite }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /favorites/1
  # PUT /favorites/1.xml
  def update
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      if @favorite.update_attributes(params[:favorite])
        format.html { redirect_to(@favorite, :notice => 'Favorite was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.xml
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to(favorites_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  # GET /trucks
  # GET /trucks.xml
  def index
    debugger
    @trucks = Truck.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @trucks }
    end
  end

  # GET /trucks/1
  # GET /trucks/1.xml
  def show
    @truck = Truck.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @truck }
    end
  end

  # GET /trucks/new
  # GET /trucks/new.xml
  def new
    @truck = Truck.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @truck }
    end
  end

  # GET /trucks/1/edit
  def edit
    @truck = Truck.find(params[:id])
  end

  # POST /trucks
  # POST /trucks.xml
  def create
    @truck = Truck.new(params[:truck])

    respond_to do |format|
      if @truck.save
        format.html { redirect_to(@truck, :notice => 'Truck was successfully created.') }
        format.xml  { render :xml => @truck, :status => :created, :location => @truck }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @truck.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trucks/1
  # PUT /trucks/1.xml
  def update
    @truck = Truck.find(params[:id])

    respond_to do |format|
      if @truck.update_attributes(params[:truck])
        format.html { redirect_to(@truck, :notice => 'Truck was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @truck.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trucks/1
  # DELETE /trucks/1.xml
  def destroy
    @truck = Truck.find(params[:id])
    @truck.destroy

    respond_to do |format|
      format.html { redirect_to(trucks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/favorites/_form.html.haml
= form_for @favorite do |f|
  -if @favorite.errors.any?
    #error_explanation
      %h2= "#{pluralize(@favorite.errors.count, "error")} prohibited this favorite from being saved:"
      %ul
        - @favorite.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/favorites/edit.html.haml
%h1 Editing favorite

= render 'form'

= link_to 'Show', @favorite
\|
= link_to 'Back', favorites_path

app/views/favorites/index.html.haml
%h1 Listing favorites

%table
  %tr
    %th
    %th
    %th

  - @favorites.each do |favorite|
    %tr
      %td= link_to 'Show', favorite
      %td= link_to 'Edit', edit_favorite_path(favorite)
      %td= link_to 'Destroy', favorite, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Favorite', new_favorite_path

app/views/favorites/new.html.haml
%h1 New favorite

= render 'form'

= link_to 'Back', favorites_path

app/views/favorites/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_favorite_path(@favorite)
\|
= link_to 'Back', favorites_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3MongoidDevise</title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'gmaps4rails' %>
  <%= javascript_include_tag :defaults %>
  <%= yield :scripts %> 
  <%= csrf_meta_tag %>
</head>
<body>
  <ul class="hmenu">
    <%= render 'devise/menu/registration_items' %>
    <%= render 'devise/menu/login_items' %>
  </ul>
  <%- flash.each do |name, msg| -%>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  <%- end -%>

<%= yield %>

</body>
</html>

app/views/trucks/_form.html.haml
= form_for @truck do |f|
  -if @truck.errors.any?
    #error_explanation
      %h2= "#{pluralize(@truck.errors.count, "error")} prohibited this truck from being saved:"
      %ul
        - @truck.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :twitter
    = f.text_field :twitter
  .field
    = f.label :latitude
    = f.text_field :location, :multiple => true, :id => "foo_location_1"
  .field
    = f.label :longitude
    = f.text_field :location, :multiple => true, :id => "foo_location_2"
  .actions
    = f.submit 'Save'

app/views/trucks/edit.html.haml
%h1 Editing truck

= render 'form'

= link_to 'Show', @truck
\|
= link_to 'Back', trucks_path

app/views/trucks/index.html.haml
%h1 Listing trucks

%table
  %tr
    %th Name
    %th Twitter
    %th Location
    %th
    %th
    %th

  - @trucks.each do |truck|
    %tr
      %td= truck.name
      %td= truck.twitter
      %td= truck.location
      %td= link_to 'Show', truck
      %td= link_to 'Edit', edit_truck_path(truck)
      %td= link_to 'Destroy', truck, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Truck', new_truck_path

app/views/trucks/new.html.haml
%h1 New truck

= render 'form'

= link_to 'Back', trucks_path

app/views/trucks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @truck.name
%p
  %b Twitter:
  = @truck.twitter
%p
  %b Location:
  = @truck.location

= link_to 'Edit', edit_truck_path(@truck)
\|
= link_to 'Back', trucks_path